export const settingsCopy = {
  en: {
    eyebrow: "Your account",
    title: "Account settings",
    intro: "Update your profile, change your password, or manage your active sessions.",
    notSignedIn: {
      title: "Not signed in",
      body: "Sign in to manage your account settings.",
      loginLabel: "Sign in",
    },
    profile: {
      title: "Profile",
      displayNameLabel: "Display name",
      displayNamePlaceholder: "Your name",
      countryLabel: "Country / Region",
      countryPlaceholder: "Search your country…",
      countrySearchHint: "Type to search",
      countryNoResults: "No results",
      saveLabel: "Save changes",
      savingLabel: "Saving…",
      successMessage: "Profile updated.",
      errorFallback: "Could not update profile. Please try again.",
    },
    password: {
      title: "Change password",
      currentLabel: "Current password",
      newLabel: "New password",
      confirmLabel: "Confirm new password",
      saveLabel: "Change password",
      savingLabel: "Changing…",
      successMessage: "Password changed. You have been signed out of all devices.",
      mismatchError: "Passwords do not match.",
      tooShortError: "New password must be at least 8 characters.",
      errorFallback: "Could not change password. Please try again.",
    },
    sessions: {
      title: "Active sessions",
      body: "Sign out of all devices, including this one. You will need to sign in again.",
      revokeLabel: "Sign out all devices",
      revokingLabel: "Signing out…",
      successMessage: "All sessions signed out.",
      errorFallback: "Could not sign out all sessions. Please try again.",
    },
  },
  de: {
    eyebrow: "Dein Konto",
    title: "Kontoeinstellungen",
    intro: "Aktualisiere dein Profil, ändere dein Passwort oder verwalte deine aktiven Sitzungen.",
    notSignedIn: {
      title: "Nicht angemeldet",
      body: "Melde dich an, um deine Kontoeinstellungen zu verwalten.",
      loginLabel: "Anmelden",
    },
    profile: {
      title: "Profil",
      displayNameLabel: "Anzeigename",
      displayNamePlaceholder: "Dein Name",
      countryLabel: "Land / Region",
      countryPlaceholder: "Land suchen…",
      countrySearchHint: "Tippe zum Suchen",
      countryNoResults: "Keine Ergebnisse",
      saveLabel: "Änderungen speichern",
      savingLabel: "Wird gespeichert…",
      successMessage: "Profil aktualisiert.",
      errorFallback: "Profil konnte nicht aktualisiert werden. Bitte versuche es erneut.",
    },
    password: {
      title: "Passwort ändern",
      currentLabel: "Aktuelles Passwort",
      newLabel: "Neues Passwort",
      confirmLabel: "Neues Passwort bestätigen",
      saveLabel: "Passwort ändern",
      savingLabel: "Wird geändert…",
      successMessage: "Passwort geändert. Du wurdest von allen Geräten abgemeldet.",
      mismatchError: "Passwörter stimmen nicht überein.",
      tooShortError: "Das neue Passwort muss mindestens 8 Zeichen lang sein.",
      errorFallback: "Passwort konnte nicht geändert werden. Bitte versuche es erneut.",
    },
    sessions: {
      title: "Aktive Sitzungen",
      body: "Melde dich von allen Geräten ab, einschließlich diesem. Du musst dich anschließend erneut anmelden.",
      revokeLabel: "Alle Geräte abmelden",
      revokingLabel: "Wird abgemeldet…",
      successMessage: "Alle Sitzungen abgemeldet.",
      errorFallback: "Sitzungen konnten nicht beendet werden. Bitte versuche es erneut.",
    },
  },
};
