export const settingsCopy = {
  en: {
    eyebrow: "Your account",
    title: "Account settings",
    intro: "Update your profile, change your password, or manage your active sessions.",
    notSignedIn: {
      title: "Not signed in",
      body: "Sign in to manage your account settings.",
      loginLabel: "Sign in",
    },
    profile: {
      title: "Profile",
      displayNameLabel: "Display name",
      displayNamePlaceholder: "Your name",
      countryLabel: "Country / Region",
      countryPlaceholder: "Search your country…",
      countrySearchHint: "Type to search",
      countryNoResults: "No results",
      saveLabel: "Save changes",
      savingLabel: "Saving…",
      successMessage: "Profile updated.",
      errorFallback: "Could not update profile. Please try again.",
    },
    password: {
      title: "Change password",
      currentLabel: "Current password",
      newLabel: "New password",
      confirmLabel: "Confirm new password",
      saveLabel: "Change password",
      savingLabel: "Changing…",
      successMessage: "Password changed. You have been signed out of all devices.",
      mismatchError: "Passwords do not match.",
      tooShortError: "New password must be at least 8 characters.",
      errorFallback: "Could not change password. Please try again.",
    },
    notifications: {
      title: "Notifications",
      pmEmailLabel: "Email me when I receive a private message",
      pmEmailHint: "When turned off, messages still arrive in your inbox — you just won't get an email alert.",
      saveLabel: "Save",
      savingLabel: "Saving…",
      successMessage: "Notification preferences saved.",
      errorFallback: "Could not save preferences. Please try again.",
      pushLabel: "Push notifications on this device",
      pushHint: "Get a notification on this device when you receive a private message.",
      pushIosHint: "Add Fat Fitness Community to your home screen to enable push notifications on iPhone/iPad.",
      pushPermissionDeniedHint: "Notifications are blocked for this site in your browser settings.",
      pushSuccessMessage: "Push notifications updated.",
      pushErrorFallback: "Could not update push notifications. Please try again.",
    },
    sessions: {
      title: "Active sessions",
      body: "Sign out of all devices, including this one. You will need to sign in again.",
      revokeLabel: "Sign out all devices",
      revokingLabel: "Signing out…",
      successMessage: "All sessions signed out.",
      errorFallback: "Could not sign out all sessions. Please try again.",
    },
    avatar: {
      title: "Profile photo",
      hint: "Upload JPG or PNG",
      changeLabel: "Change photo",
      uploadLabel: "Upload",
      cancelLabel: "Cancel",
      savingLabel: "Saving…",
      successMessage: "Photo updated.",
      errorFallback: "Could not save photo. Please try again.",
      fileTooLargeError: "File is too large (max 8 MB).",
      invalidFileError: "Please select a JPG or PNG image.",
    },
  },
  de: {
    eyebrow: "Dein Konto",
    title: "Kontoeinstellungen",
    intro: "Aktualisiere dein Profil, ändere dein Passwort oder verwalte deine aktiven Sitzungen.",
    notSignedIn: {
      title: "Nicht angemeldet",
      body: "Melde dich an, um deine Kontoeinstellungen zu verwalten.",
      loginLabel: "Anmelden",
    },
    profile: {
      title: "Profil",
      displayNameLabel: "Anzeigename",
      displayNamePlaceholder: "Dein Name",
      countryLabel: "Land / Region",
      countryPlaceholder: "Land suchen…",
      countrySearchHint: "Tippe zum Suchen",
      countryNoResults: "Keine Ergebnisse",
      saveLabel: "Änderungen speichern",
      savingLabel: "Wird gespeichert…",
      successMessage: "Profil aktualisiert.",
      errorFallback: "Profil konnte nicht aktualisiert werden. Bitte versuche es erneut.",
    },
    password: {
      title: "Passwort ändern",
      currentLabel: "Aktuelles Passwort",
      newLabel: "Neues Passwort",
      confirmLabel: "Neues Passwort bestätigen",
      saveLabel: "Passwort ändern",
      savingLabel: "Wird geändert…",
      successMessage: "Passwort geändert. Du wurdest von allen Geräten abgemeldet.",
      mismatchError: "Passwörter stimmen nicht überein.",
      tooShortError: "Das neue Passwort muss mindestens 8 Zeichen lang sein.",
      errorFallback: "Passwort konnte nicht geändert werden. Bitte versuche es erneut.",
    },
    notifications: {
      title: "Benachrichtigungen",
      pmEmailLabel: "E-Mail erhalten, wenn ich eine private Nachricht bekomme",
      pmEmailHint: "Wenn deaktiviert, landen Nachrichten weiterhin in deinem Postfach – du erhältst nur keine E-Mail-Benachrichtigung.",
      saveLabel: "Speichern",
      savingLabel: "Wird gespeichert…",
      successMessage: "Benachrichtigungseinstellungen gespeichert.",
      errorFallback: "Einstellungen konnten nicht gespeichert werden. Bitte versuche es erneut.",
      pushLabel: "Push-Benachrichtigungen auf diesem Gerät",
      pushHint: "Erhalte eine Benachrichtigung auf diesem Gerät, wenn du eine private Nachricht bekommst.",
      pushIosHint: "Füge Fat Fitness Community zu deinem Startbildschirm hinzu, um Push-Benachrichtigungen auf iPhone/iPad zu aktivieren.",
      pushPermissionDeniedHint: "Benachrichtigungen sind für diese Seite in deinen Browser-Einstellungen blockiert.",
      pushSuccessMessage: "Push-Benachrichtigungen aktualisiert.",
      pushErrorFallback: "Push-Benachrichtigungen konnten nicht aktualisiert werden. Bitte versuche es erneut.",
    },
    sessions: {
      title: "Aktive Sitzungen",
      body: "Melde dich von allen Geräten ab, einschließlich diesem. Du musst dich anschließend erneut anmelden.",
      revokeLabel: "Alle Geräte abmelden",
      revokingLabel: "Wird abgemeldet…",
      successMessage: "Alle Sitzungen abgemeldet.",
      errorFallback: "Sitzungen konnten nicht beendet werden. Bitte versuche es erneut.",
    },
    avatar: {
      title: "Profilbild",
      hint: "JPG oder PNG · wird in Forum-Beiträgen und deinem Konto angezeigt.",
      changeLabel: "Foto ändern",
      uploadLabel: "Hochladen",
      cancelLabel: "Abbrechen",
      savingLabel: "Wird gespeichert…",
      successMessage: "Foto aktualisiert.",
      errorFallback: "Foto konnte nicht gespeichert werden. Bitte versuche es erneut.",
      fileTooLargeError: "Datei ist zu groß (max. 8 MB).",
      invalidFileError: "Bitte wähle ein JPG- oder PNG-Bild.",
    },
  },
};
